--------------------------------------------------------
--  File created - Wednesday-November-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GESTION_ANIMAUX
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_ANIMAUX" 
   (	"ID_ANIMAL" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"RACE" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"DATE_ENTREE" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_EVENNEMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_EVENNEMENT" 
   (	"REFERENCE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"SUJET" VARCHAR2(20 BYTE), 
	"DATE_EVENNEMENT" DATE, 
	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"DUREE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_PERSONNEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_PERSONNEL" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"SALAIRE" FLOAT(126), 
	"NUM_TEL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_PRODUIT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_PRODUIT" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(20 BYTE), 
	"DATE_PRODUCTION" DATE, 
	"DATE_EXPIRATION" DATE, 
	"PRIX" FLOAT(126), 
	"QUANTITE" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GESTION_VISITEUR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_VISITEUR" 
   (	"NUMERO_VISITEUR" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"NUM_TEL" NUMBER, 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.GESTION_ANIMAUX
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_EVENNEMENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_PERSONNEL
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_PRODUIT
SET DEFINE OFF;
REM INSERTING into SYSTEM.GESTION_VISITEUR
SET DEFINE OFF;
