--------------------------------------------------------
--  Fichier créé - mardi-novembre-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GESTION_EVENNEMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_EVENNEMENT" 
   (	"REFERENCE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"SUJET" VARCHAR2(20 BYTE), 
	"DATE_EVENNEMENT" DATE, 
	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"DUREE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.GESTION_EVENNEMENT
SET DEFINE OFF;
