--------------------------------------------------------
--  Fichier créé - mardi-novembre-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GESTION_PRODUIT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GESTION_PRODUIT" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_EXPIRATION" DATE, 
	"PRIX" FLOAT(126), 
	"QUANTITE" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.GESTION_PRODUIT
SET DEFINE OFF;
